---
#- name: obtain token
#  shell: docker swarm join-token -q worker 
#  register: swarm_token
  
- name: obtain token
  shell: docker swarm join-token worker |grep token |awk ' { print $2 } '
  register: swarm_token

