---
- name: Worker nodes join the swarm
  shell: docker swarm join --token {{ hostvars.server01.swarm_token_worker.stdout }} --advertise-addr {{interfaces.{{ansible_hostname}}.loopback}} {{ interface{{interfaces.server01.loopback}}:2377
  

