---
- hosts: spines:leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - configure-interfaces
    - mv-ntp-mgmt
    - quagga

- hosts: mgmtserver:workerservers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - install-docker-ifupdown2
    - configure-interfaces-servers
    - deploy-roh
#    - deploy-containers

- hosts: mgmtserver
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - initiate-swarm-manager
    - obtain-swarm-token

- hosts: workerservers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
     - join-the-swarm

- hosts: mgmtserver
  user: cumulus
  become: yes
  become_method: sudo
  roles:
     - create-service
