- name: Install Docker Repo's Public Key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Docker Source
  shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install Docker, Ifupdown2 and PIP
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - docker-ce
    - ifupdown2
    - python-pip

- name: Add Docker-py Module
  pip: name=docker-py

- name: Allow IfUpdown2 to Run at Boot
  lineinfile:
    dest: "/lib/systemd/system/networking.service"
    regexp: '^RemainAfterExit'
    insertafter: '^\[Service\]'
    line: 'RemainAfterExit=yes'

- name: Start the Docker Daemon (if it isn't already running)
  service: name=docker state=started

