
# This task configures /etc/network/interfaces on ifupdown2. The variables for
# which interfaces are neighbors and networks come from the group_vars/all file.
- name: configure /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reload networking

- name: Bring Loopback Interface Up
  shell: "ifup lo"

- name: Bring Neighbor Interfaces Up
  shell: "ifup {{item}}"
  with_items: "{{ interfaces[inventory_hostname].neighbors }}"


