---
- name: Promote other workers to be backup managers
  shell: docker node promote server02 server03

- name: Create Service
  shell: docker service create --name apache_web --replicas {{services.replicas}} --publish 8080:80 php:5.6-apache
